### ISSUE TITLE
Exposing a faketty library for use with CommandExt::pre_exec

### ISSUE THREAD

**Issue by oddlama** [dtolnay/faketty#10]
Thanks for making this ❤️. Have you considered exposing this functionality as a library? When paired with [`CommandExt::pre_exec`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.pre_exec), this would provide the awesome functionality to run commands in a pseudo terminal for other projects. For example by exposing a simple higher order function, this could even allow specifying a custom fake-terminal size or passing through the actual terminal's Termios:

```rust
fn init_faketty(winsize: Option<Winsize>, termios: Option<Termios>) -> FnMut<std::io::Result()> + Send + Sync
```

Would this be in-scope for this project?

**Comment by dtolnay** [comment]
I would prefer not to make that part of this project.
